# FROM node:18 as build
FROM node:20.8-alpine3.18 as build
WORKDIR /app
COPY package.json ./
RUN yarn install
COPY . .
RUN yarn build:prod

# Stage 2: Production environment
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
