version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - 'mongo_data:/data/db'
    command: mongod --bind_ip_all
    networks:
      - live-workspace-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    command: redis-server --notify-keyspace-events KEx
    networks:
      - live-workspace-network

  server:
    container_name: server-test
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '8420:8420'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=8420
      - MONGO_URL=mongodb://mongodb:27017/live-workspace
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=Som3thinGSe3cret
      - AWS_ACCESS_KEY_ID=AKIAUXTM3KHW3XHKRK6E
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=ap-southeast-1
      - AWS_BUCKET_NAME=liveworkspace.senytera
      - AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE=1
    depends_on:
      - mongodb
      - redis
    command: yarn start:dev
    networks:
      - live-workspace-network

networks:
  live-workspace-network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
