version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
    command: redis-server --notify-keyspace-events KEx
    networks:
      - live-workspace-network

  server:
    container_name: server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '8420:8420'
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env.ec2
    depends_on:
      - redis
    command: yarn start:dev
    networks:
      - live-workspace-network

networks:
  live-workspace-network:
    driver: bridge

volumes:
  redis_data:
