# Stage 1: Builder
FROM node:18 as builder
WORKDIR /app
COPY package.json yarn.lock ./
# Install dependencies
RUN yarn install
# Copy source code
COPY . .
# Build the application
RUN yarn build
RUN yarn install --production

# Stage 2: Final
FROM node:18-alpine
WORKDIR /app
# Copy everything from the builder stage
COPY --from=builder /app .
# Expose the port
EXPOSE 3000
# Command default to run the application
CMD ["yarn", "start:prod"]
